engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
    config:
      standard: PSR1,PSR2
  phpmd:
    enabled: true
    config:
      file_extensions:
      - php
      - inc
  phan:
    enabled: true
    config:
      file_extensions: php
ratings:
  paths:
  - "**.php"
exclude_paths:
  - "vendor/*"

