build:
    environment:
        php: '5.4.28'
    dependencies:
        inference:
            - command: 'composer install --no-interaction --no-dev --prefer-dist'

tools:
    php_sim: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    
