language: php

php:
  - 5.6
  - 7.2

sudo: false

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

before_install:
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar
  - phpenv config-rm xdebug.ini

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - php ./composer.phar self-update
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script:
  - ./bin/phpunit

addons:
  code_climate:
    repo_token: 7881a44b994be3638100a30a9c3ec441c05e5aed05d69925a1f057a8f06508e5 

after_script:
  - ./bin/test-reporter
