OpenOrchestra\ModelInterface\Model\NodeInterface:
    constraints:
        - OpenOrchestra\Backoffice\Validator\Constraints\UniqueNodeOrder: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\CheckVariableRoutePatternInMenu: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\UniqueNodeSpecialPage: ~
