OpenOrchestra\ModelBundle\Document\Site:
    constraints:
        - OpenOrchestra\Backoffice\Validator\Constraints\CheckMainAliasPresence: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\UniqueMainAlias: ~
