OpenOrchestra\ModelInterface\Model\SiteInterface:
    constraints:
        - OpenOrchestra\Backoffice\Validator\Constraints\CheckMainAliasPresence: ~
        - OpenOrchestra\Backoffice\Validator\Constraints\UniqueMainAlias: ~
