Model\PHPOrchestraCMSBundle\Site:
    collection: site
    fields:
        siteId: integer
        domain: string
        alias: string
        defaultLanguage: string
        languages: string
        blocks: string


Model\PHPOrchestraCMSBundle\Block:
    collection: node
    isEmbedded: true
    fields:
        component: string
        attributes: raw


Model\PHPOrchestraCMSBundle\Node:
    collection: node
    fields:
        nodeId: string
        nodeType: string
        siteId: integer
        parentId: string
        path: string
        alias: string
        name: string
        version: integer
        language: string
        status: string
        deleted: boolean
        templateId: string
        theme: string
        inMenu: boolean
        inFooter: boolean
        areas: raw
    embeddedsMany:
        blocks: {class: Model\PHPOrchestraCMSBundle\Block}


Model\PHPOrchestraCMSBundle\Template:
    collection: template
    fields:
        templateId: string
        siteId: integer
        name: string
        version: integer
        language: string
        status: string
        deleted: boolean
        areas: raw
        boDirection: string
    embeddedsMany:
        blocks: {class: Model\PHPOrchestraCMSBundle\Block}


Model\PHPOrchestraCMSBundle\ContentAttribute:
    collection: contentAttribute
    isEmbedded: true
    fields:
        name: string
        value: string


Model\PHPOrchestraCMSBundle\Content:
    collection: content
    fields:
        contentId: string
        contentType: string
        version: integer
        language: string
        status: string
        shortName: string
        contentTypeVersion: integer
        deleted: boolean
    embeddedsMany:
        attributes: {class: Model\PHPOrchestraCMSBundle\ContentAttribute}

Model\PHPOrchestraCMSBundle\ContentType:
    collection: contentType
    fields:
        contentTypeId: string
        name: raw
        version: integer
        status: string
        deleted: boolean
        fields: raw


Model\PHPOrchestraCMSBundle\User:
    collection: user
    fields:
        login: string
        hash: string
        salt: string
        firstName: string
        lastName: string
        email: string
        addresses: string


Model\PHPOrchestraCMSBundle\ListIndex:
    collection: listIndex
    fields:
        nodeId: string
        contentId: string

Model\PHPOrchestraCMSBundle\FieldIndex:
    collection: fieldIndex
    fields:
        fieldName: string
        fieldType: string