parameters:
    open_orchestra_log.processor.log_user.class: OpenOrchestra\LogBundle\Processor\LogUserProcessor

services:
    open_orchestra_log.processor.log_user:
        class: '%open_orchestra_log.processor.log_user.class%'
        arguments:
            - '@security.token_storage'
            - '@request_stack'
            - '@open_orchestra_backoffice.context_backoffice_manager'
        tags:
            - { name: monolog.processor, method: processRecord, channel: openorchestra }
