parameters:
    open_orchestra_log.subscriber.node.class: OpenOrchestra\LogBundle\EventSubscriber\LogNodeSubscriber
    open_orchestra_log.subscriber.content.class: OpenOrchestra\LogBundle\EventSubscriber\LogContentSubscriber
    open_orchestra_log.subscriber.content_type.class: OpenOrchestra\LogBundle\EventSubscriber\LogContentTypeSubscriber
    open_orchestra_log.subscriber.keyword.class: OpenOrchestra\LogBundle\EventSubscriber\LogKeywordSubscriber
    open_orchestra_log.subscriber.group.class: OpenOrchestra\LogBundle\EventSubscriber\LogGroupSubscriber
    open_orchestra_log.subscriber.redirection.class: OpenOrchestra\LogBundle\EventSubscriber\LogRedirectionSubscriber
    open_orchestra_log.subscriber.site.class: OpenOrchestra\LogBundle\EventSubscriber\LogSiteSubscriber
    open_orchestra_log.subscriber.status.class: OpenOrchestra\LogBundle\EventSubscriber\LogStatusSubscriber
    open_orchestra_log.subscriber.theme.class: OpenOrchestra\LogBundle\EventSubscriber\LogThemeSubscriber
    open_orchestra_log.subscriber.user.class: OpenOrchestra\LogBundle\EventSubscriber\LogUserSubscriber

services:
    open_orchestra_log.subscriber.node:
        class: '%open_orchestra_log.subscriber.node.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.content:
        class: '%open_orchestra_log.subscriber.content.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.content_type:
        class: '%open_orchestra_log.subscriber.content_type.class%'
        arguments:
            - '@logger'
            - '@open_orchestra_backoffice.context_manager'
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.keyword:
        class: '%open_orchestra_log.subscriber.keyword.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.group:
        class: '%open_orchestra_log.subscriber.group.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.redirection:
        class: '%open_orchestra_log.subscriber.redirection.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.site:
        class: '%open_orchestra_log.subscriber.site.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.status:
        class: '%open_orchestra_log.subscriber.status.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.theme:
        class: '%open_orchestra_log.subscriber.theme.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
    open_orchestra_log.subscriber.user:
        class: '%open_orchestra_log.subscriber.user.class%'
        arguments: ['@logger']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: openorchestra }
