parameters:
    open_orchestra_log.transformer.log_collection.class: OpenOrchestra\LogBundle\Transformer\LogCollectionTransformer
    open_orchestra_log.transformer.log.class: OpenOrchestra\LogBundle\Transformer\LogTransformer

services:
    open_orchestra_log.transformer.log_collection:
        class: '%open_orchestra_log.transformer.log_collection.class%'
        arguments:
            - '@doctrine_mongodb.odm.cache.array'
            - '%open_orchestra_log.facade.log_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_log.transformer.log:
        class: '%open_orchestra_log.transformer.log.class%'
        arguments:
            - '@doctrine_mongodb.odm.cache.array'
            - '%open_orchestra_log.facade.log.class%'
            - '@translator'
        tags:
            - { name: open_orchestra_api.transformer.strategy}
