parameters:
    open_orchestra_workflow_admin.type.workflow_profile.class: OpenOrchestra\Workflow\Form\Type\WorkflowProfileType

services:
    open_orchestra_workflow_admin.type.workflow_profile:
        class: '%open_orchestra_workflow_admin.type.workflow_profile.class%'
        arguments:
            - '%open_orchestra_model.document.workflow_profile.class%'
            - '%open_orchestra_base.administration_languages%'
        tags:
            - { name: form.type, alias: oo_workflow_profile }
