parameters:
    open_orchestra_workflow_admin.manager.authorization_workflow_right.class: OpenOrchestra\Workflow\Manager\AuthorizationWorkflowRightManager
    open_orchestra_workflow_admin.manager.workflow_right.class              : OpenOrchestra\WorkflowAdminBundle\Manager\WorkflowRightManager

services:
    open_orchestra_workflow_admin.manager.authorization_workflow_right:
        class: '%open_orchestra_workflow_admin.manager.authorization_workflow_right.class%'
        arguments:
            - '%open_orchestra_model.document.authorization.class%'
    open_orchestra_workflow_admin.manager.workflow_right:
        class: '%open_orchestra_workflow_admin.manager.workflow_right.class%'
        arguments:
            - '@open_orchestra_model.repository.content_type'
            - '@open_orchestra_model.repository.workflow_right'
            - '@open_orchestra_workflow_admin.manager.authorization_workflow_right'
            - '%open_orchestra_model.document.workflow_right.class%'
            - '%open_orchestra_model.document.reference.class%'
