parameters:
    open_orchestra_workflow_admin.factory.transition.class: OpenOrchestra\Workflow\Factory\TransitionFactory

services:
    open_orchestra_workflow_admin.factory.transition:
        class: '%open_orchestra_workflow_admin.factory.transition.class%'
        arguments:
            - '%open_orchestra_model.document.workflow_transition.class%'
