parameters:
    open_orchestra_workflow_admin.subscriber.add_workflow_link.class: OpenOrchestra\WorkflowAdminBundle\EventSubscriber\AddWorkFlowLinkSubscriber
    open_orchestra_workflow_admin.subscriber.add_workflow_function.class: OpenOrchestra\WorkflowAdminBundle\EventSubscriber\AddWorkFlowFunctionSubscriber
services:
    open_orchestra_workflow_admin.subscriber.add_workflow_link:
        class: '%open_orchestra_workflow_admin.subscriber.add_workflow_link.class%'
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_workflow_admin.subscriber.add_workflow_function:
        class: '%open_orchestra_workflow_admin.subscriber.add_workflow_function.class%'
        arguments:
            - '@open_orchestra_user.repository.user'
            - '@doctrine_mongodb.odm.default_document_manager'
        tags:
            - { name: kernel.event_subscriber }
