parameters:
    open_orchestra_workflow_admin.subscriber.group_profile.class            : OpenOrchestra\WorkflowAdminBundle\EventSubscriber\AddGroupWorkflowProfileSubscriber
    open_orchestra_workflow_admin.subscriber.statusable_choice_status.class : OpenOrchestra\WorkflowAdminBundle\EventSubscriber\StatusableChoiceStatusSubscriber

services:
    open_orchestra_workflow_admin.subscriber.group_profile:
        class: '%open_orchestra_workflow_admin.subscriber.group_profile.class%'
        arguments:
            - '@open_orchestra_model.repository.workflow_profile'
            - '@open_orchestra_model.repository.content_type'
            - '@open_orchestra_workflow_admin.transformer.group_workflow_profile_collection'
            - '@open_orchestra_backoffice.context_backoffice_manager'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_workflow_admin.subscriber.content_choice_status:
        class: '%open_orchestra_workflow_admin.subscriber.statusable_choice_status.class%'
        arguments:
            - '@open_orchestra_model.repository.status'
            - '@security.authorization_checker'
            - '@object_manager'
            -
                label: 'open_orchestra_backoffice.form.content.status'
                group_id: 'property'
                sub_group_id: 'publication'
