parameters:
    open_orchestra_workflow_admin.subscriber.group_profile.class: OpenOrchestra\WorkflowAdminBundle\EventSubscriber\AddGroupWorkflowProfileSubscriber

services:
    open_orchestra_workflow_admin.subscriber.group_profile:
        class: '%open_orchestra_workflow_admin.subscriber.group_profile.class%'
        arguments:
            - '@open_orchestra_model.repository.workflow_profile'
            - '@open_orchestra_model.repository.content_type'
            - '@open_orchestra_workflow_admin.transformer.workflow_profil_collection'
            - '@open_orchestra_backoffice.context_manager'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }
