parameters:
    open_orchestra_workflow.voter.node_workflow.class   : OpenOrchestra\Workflow\Security\Authorization\Voter\NodeWorkflowVoter
    open_orchestra_workflow.voter.content_workflow.class: OpenOrchestra\Workflow\Security\Authorization\Voter\NodeWorkflowVoter

services:
    open_orchestra_workflow.voter.node_workflow:
        class: '%open_orchestra_workflow.voter.node_workflow.class%'
        arguments:
            - '@open_orchestra_group.perimeter_manager'
            - '@open_orchestra_model.repository.workflow_profile'
        tags:
            - { name: security.voter }
    open_orchestra_workflow.voter.content_workflow:
        class: '%open_orchestra_workflow.voter.content_workflow.class%'
        arguments:
            - '@open_orchestra_group.perimeter_manager'
            - '@open_orchestra_model.repository.workflow_profile'
        tags:
            - { name: security.voter }
