parameters:
    open_orchestra_backoffice.authorize_edition.manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\AuthorizeEditionManager
    open_orchestra_backoffice.authorize_edition.statusable.class: OpenOrchestra\Backoffice\AuthorizeEdition\StatusableStrategy
    open_orchestra_backoffice.authorize_edition.node_version.class: OpenOrchestra\Backoffice\AuthorizeEdition\NodeVersionStrategy
    open_orchestra_backoffice.authorize_edition.node_edition_role.class: OpenOrchestra\Backoffice\AuthorizeEdition\NodeEditionRoleStrategy
    open_orchestra_backoffice.authorize_edition.content_version.class: OpenOrchestra\Backoffice\AuthorizeEdition\ContentVersionStrategy
    open_orchestra_backoffice.authorize_edition.template.class: OpenOrchestra\Backoffice\AuthorizeEdition\TemplateStrategy

services:
    open_orchestra_backoffice.authorize_edition.manager:
        class: %open_orchestra_backoffice.authorize_edition.manager.class%

    open_orchestra_backoffice.authorize_edition.statusable:
        class: %open_orchestra_backoffice.authorize_edition.statusable.class%
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
    open_orchestra_backoffice.authorize_edition.node_version:
        class: %open_orchestra_backoffice.authorize_edition.node_version.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
    open_orchestra_backoffice.authorize_edition.node_edition_role:
        class: %open_orchestra_backoffice.authorize_edition.node_edition_role.class%
        arguments:
            - @security.authorization_checker
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
    open_orchestra_backoffice.authorize_edition.content_version:
        class: %open_orchestra_backoffice.authorize_edition.content_version.class%
        arguments:
            - @open_orchestra_model.repository.content
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
    open_orchestra_backoffice.authorize_edition.template:
        class: %open_orchestra_backoffice.authorize_edition.template.class%
        arguments:
            - @open_orchestra_model.repository.template
            - @security.authorization_checker
        tags:
            - { name: open_orchestra_backoffice.authorize_edition.strategy }
