parameters:
    open_orchestra_backoffice.delete_trashcan_entity.manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\DeleteTrashcanEntityManager
    open_orchestra_backoffice.delete_trashcan_entity.node.class: OpenOrchestra\Backoffice\DeleteTrashcanEntity\Strategies\DeleteTrashCanNodeStrategy
    open_orchestra_backoffice.delete_trashcan_entity.content.class: OpenOrchestra\Backoffice\DeleteTrashcanEntity\Strategies\DeleteTrashCanContentStrategy

services:
    open_orchestra_backoffice.delete_trashcan_entity.manager:
        class: %open_orchestra_backoffice.delete_trashcan_entity.manager.class%

    open_orchestra_backoffice.delete_trashcan_entity.node_version:
        class: %open_orchestra_backoffice.delete_trashcan_entity.node.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_model.repository.trash_item
            - @event_dispatcher
            - @object_manager
        tags:
            - { name: open_orchestra_backoffice.delete_trashcan_entity.strategy }
    open_orchestra_backoffice.delete_trashcan_entity.content_version:
        class: %open_orchestra_backoffice.delete_trashcan_entity.content.class%
        arguments:
            - @open_orchestra_model.repository.content
            - @event_dispatcher
            - @object_manager
        tags:
            - { name: open_orchestra_backoffice.delete_trashcan_entity.strategy }
