parameters:
    open_orchestra_backoffice.display_block.manager.class: OpenOrchestra\Backoffice\DisplayBlock\DisplayBlockManager
    open_orchestra_backoffice.display.tiny_mce_wysiwyg.class: OpenOrchestra\Backoffice\DisplayBlock\Strategies\TinyMCEWysiwygStrategy
    open_orchestra_backoffice.display.default.class: OpenOrchestra\Backoffice\DisplayBlock\Strategies\DefaultStrategy

services:
    open_orchestra_backoffice.display_block_manager:
        class: '%open_orchestra_backoffice.display_block.manager.class%'
        arguments:
            - '@templating'
            - '@open_orchestra_backoffice.display.default'

    open_orchestra_backoffice.display.default:
        class: '%open_orchestra_backoffice.display.default.class%'

    open_orchestra_backoffice.display.tiny_mce_wysiwyg:
        class: '%open_orchestra_backoffice.display.tiny_mce_wysiwyg.class%'
        tags:
            - { name: open_orchestra_backoffice.display_block.strategy }
