parameters:

#--[CUSTOM FIELDS]--------------#
    open_orchestra_backoffice.field_types:
        text:
            label: open_orchestra_backoffice.form.field_type.custom_type.text
            type: text
            deserialize_type: string
            search: text
            default_value:
                type: text
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                max_length:
                    default_value: 25
                required:
                    default_value: false
        textarea:
            label: open_orchestra_backoffice.form.field_type.custom_type.textarea
            type: textarea
            deserialize_type: string
            search: text
            default_value:
                type: textarea
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                max_length:
                    default_value: 100
                required:
                    default_value: false
        tinymce:
            label: open_orchestra_backoffice.form.field_type.custom_type.wysiwyg
            type: oo_tinymce
            deserialize_type: string
            search: text
            default_value:
                type: oo_tinymce
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                max_length:
                    default_value: 500
                required:
                    default_value: false
        integer:
            label: open_orchestra_backoffice.form.field_type.custom_type.integer
            type: integer
            deserialize_type: integer
            search: number
            default_value:
                type: integer
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                rounding_mode:
                    default_value: 0
                grouping:
                    default_value: 0
                required:
                    default_value: false
        email:
            label: open_orchestra_backoffice.form.field_type.custom_type.email
            type: email
            deserialize_type: string
            search: text
            default_value:
                type: email
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                required:
                    default_value: false
        choice:
            label: open_orchestra_backoffice.form.field_type.custom_type.choice
            type: oo_field_choice
            deserialize_type: array
            search: text
            default_value:
                type: oo_choices_option
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                required:
                    default_value: false
                multiple:
                    default_value: false
                expanded:
                    default_value: false
                choices: ~
        money:
            label: open_orchestra_backoffice.form.field_type.custom_type.money
            type: money
            deserialize_type: float
            search: text
            default_value:
                type: money
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
            options:
                required:
                    default_value: false
                currency:
                    default_value: EUR
                precision:
                    default_value: 2
        hidden:
            label: open_orchestra_backoffice.form.field_type.custom_type.hidden
            type: hidden
            default_value:
                type: text
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: true
        date:
            label: open_orchestra_backoffice.form.field_type.custom_type.date
            type: oo_date_picker
            search: date
            deserialize_type: DateTime
            default_value:
                type: date
                options:
                    label: open_orchestra_backoffice.form.field_type.default_value
                    required: false
                    format: yyyy-MM-dd
                    widget: single_text
                    input: string
            options:
                required:
                    default_value: false
                format:
                    default_value: dd-MM-yyyy
                widget:
                    default_value: choice
                input:
                    default_value: string
        embedded_content:
            label: open_orchestra_backoffice.form.field_type.custom_type.content
            type: oo_content_choice
            deserialize_type: OpenOrchestra\ApiBundle\Facade\ContentFacade
            search: text
            options:
                required:
                    default_value: false
                content_search: ~

    open_orchestra_backoffice.options:
        orchestra_default_value_choice:
            type: oo_choices_option
            label: open_orchestra_backoffice.form.field_type.default_value
            required: false
        max_length:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.max_length
            required: true
        required:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.required_field
            required: false
        grouping:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.format
            required: true
        rounding_mode:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.rounding_mode
            required: true
        multiple:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.multiple
            required: false
        expanded:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.expanded
            required: false
        choices:
            type: oo_choices_option
            label: open_orchestra_backoffice.form.orchestra_fields.choices
            required: true
        currency:
            type: text
            label: open_orchestra_backoffice.form.orchestra_fields.currency
            required: true
        precision:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.precision
            required: true
        format:
            type: text
            label: open_orchestra_backoffice.form.orchestra_fields.date_format
            required: true
        widget:
            type: oo_date_widget_option
            label: open_orchestra_backoffice.form.orchestra_fields.widget
            required: true
        input:
            type: hidden
            label: open_orchestra_backoffice.form.orchestra_fields.date_format
            required: true
        content_search:
            type: oo_content_search
            label: false
            required: true
