parameters:
    php_orchestra_backoffice.type.template.class: PHPOrchestra\BackofficeBundle\Form\Type\TemplateType
    php_orchestra_backoffice.type.node.class: PHPOrchestra\BackofficeBundle\Form\Type\NodeType
    php_orchestra_backoffice.type.area.class: PHPOrchestra\BackofficeBundle\Form\Type\AreaType
    php_orchestra_backoffice.type.template_area.class: PHPOrchestra\BackofficeBundle\Form\Type\TemplateAreaType
    php_orchestra_backoffice.type.block.class: PHPOrchestra\BackofficeBundle\Form\Type\BlockType
    php_orchestra_backoffice.type.existing_block_choice.class: PHPOrchestra\BackofficeBundle\Form\Type\ExistingBlockChoiceType
    php_orchestra_backoffice.type.orchestra_block.class: PHPOrchestra\BackofficeBundle\Form\Type\BlockChoiceType

services:
    # Template form type
    php_orchestra_cms.type.template:
        class: %php_orchestra_backoffice.type.template.class%
        arguments:
            - %php_orchestra_model.document.template.class%
        tags:
            - { name: form.type, alias: template }
    # Node form type
    php_orchestra_backoffice.type.node:
        class: %php_orchestra_backoffice.type.node.class%
        arguments:
            - %php_orchestra_model.document.node.class%
        tags:
            - { name: form.type, alias: node }
    # Area form type
    php_orchestra_backoffice.type.area:
        class: %php_orchestra_backoffice.type.area.class%
        tags:
            - { name: form.type, alias: area }
    php_orchestra_backoffice.type.template_area:
        class: %php_orchestra_backoffice.type.template_area.class%
        tags:
            - { name: form.type, alias: template_area }
    # Block form type
    php_orchestra_backoffice.type.block:
        class: %php_orchestra_backoffice.type.block.class%
        arguments:
            - @php_orchestra_backoffice.generate_form_manager
        tags:
            - { name: form.type, alias: block }
    php_orchestra_backoffice.type.existing_block_choice:
        class: %php_orchestra_backoffice.type.existing_block_choice.class%
        arguments:
            - @php_orchestra_model.repository.node
        tags:
            - { name: form.type, alias: existing_block }

    php_orchestra_backoffice.type.orchestra_block:
        class: %php_orchestra_backoffice.type.orchestra_block.class%
        arguments: [%php_orchestra.blocks%]
        tags:
            - { name: form.type, alias: orchestra_block }
    # Site Form Builder
    php_orchestra_cms.type.site:
        class: PHPOrchestra\BackofficeBundle\Form\Type\SiteType
        arguments:
            - %php_orchestra_model.document.site.class%
        tags:
            - { name: form.type, alias: site }
