parameters:
    php_orchestra_backoffice.type.template.class: PHPOrchestra\BackofficeBundle\Form\Type\TemplateType
    php_orchestra_backoffice.type.node.class: PHPOrchestra\BackofficeBundle\Form\Type\NodeType
    php_orchestra_backoffice.type.area.class: PHPOrchestra\BackofficeBundle\Form\Type\AreaType
    php_orchestra_backoffice.type.template_area.class: PHPOrchestra\BackofficeBundle\Form\Type\TemplateAreaType
    php_orchestra_backoffice.type.block.class: PHPOrchestra\BackofficeBundle\Form\Type\BlockType
    php_orchestra_backoffice.type.existing_block_choice.class: PHPOrchestra\BackofficeBundle\Form\Type\ExistingBlockChoiceType
    php_orchestra_backoffice.type.orchestra_block.class: PHPOrchestra\BackofficeBundle\Form\Type\BlockChoiceType
    php_orchestra_backoffice.type.content.class : PHPOrchestra\BackofficeBundle\Form\Type\ContentType
    php_orchestra_backoffice.type.content_type.class: PHPOrchestra\BackofficeBundle\Form\Type\ContentTypeType
    php_orchestra_backoffice.document.content_attribute.class : PHPOrchestra\ModelBundle\Document\ContentAttribute
    php_orchestra_backoffice.type.orchestra_choice.class: PHPOrchestra\BackofficeBundle\Form\Type\OrchestraChoiceType
    php_orchestra_backoffice.type.status.class: PHPOrchestra\BackofficeBundle\Form\Type\StatusType
    php_orchestra_backoffice.type.field_type.class: PHPOrchestra\BackofficeBundle\Form\Type\FieldTypeType
    php_orchestra_backoffice.type.field_option.class: PHPOrchestra\BackofficeBundle\Form\Type\FieldOptionType

services:
    # Template form type
    php_orchestra_cms.type.template:
        class: %php_orchestra_backoffice.type.template.class%
        arguments:
            - %php_orchestra_model.document.template.class%
        tags:
            - { name: form.type, alias: template }
    # Node form type
    php_orchestra_backoffice.type.node:
        class: %php_orchestra_backoffice.type.node.class%
        arguments:
            - %php_orchestra_model.document.node.class%
        tags:
            - { name: form.type, alias: node }
    # Area form type
    php_orchestra_backoffice.type.area:
        class: %php_orchestra_backoffice.type.area.class%
        tags:
            - { name: form.type, alias: area }
    php_orchestra_backoffice.type.template_area:
        class: %php_orchestra_backoffice.type.template_area.class%
        tags:
            - { name: form.type, alias: template_area }
    # Block form type
    php_orchestra_backoffice.type.block:
        class: %php_orchestra_backoffice.type.block.class%
        arguments:
            - @php_orchestra_backoffice.generate_form_manager
        tags:
            - { name: form.type, alias: block }
    php_orchestra_backoffice.type.existing_block_choice:
        class: %php_orchestra_backoffice.type.existing_block_choice.class%
        arguments:
            - @php_orchestra_model.repository.node
        tags:
            - { name: form.type, alias: existing_block }

    php_orchestra_backoffice.type.orchestra_block:
        class: %php_orchestra_backoffice.type.orchestra_block.class%
        arguments: [%php_orchestra.blocks%]
        tags:
            - { name: form.type, alias: orchestra_block }
    # Site Form Builder
    php_orchestra_cms.type.site:
        class: PHPOrchestra\BackofficeBundle\Form\Type\SiteType
        arguments:
            - %php_orchestra_model.document.site.class%
        tags:
            - { name: form.type, alias: site }
    # Content Type Form Builder
    php_orchestra_backoffice.type.content_type:
        class: %php_orchestra_backoffice.type.content_type.class%
        arguments:
            - %php_orchestra_model.document.content_type.class%
            - @translator
        tags:
            - { name: form.type, alias: content_type }
    php_orchestra_backoffice.type.field_type:
        class: %php_orchestra_backoffice.type.field_type.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: field_type }
    php_orchestra_backoffice.type.field_option:
        class: %php_orchestra_backoffice.type.field_option.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: field_option }

    # Status Type
    php_orchestra_backoffice.type.status:
        class: %php_orchestra_backoffice.type.status.class%
        tags:
            - { name: form.type, alias: orchestra_status }

    # Content Form Builder
    php_orchestra_backoffice.type.content:
        class: %php_orchestra_backoffice.type.content.class%
        arguments:
            - @php_orchestra_model.repository.content_type
            - %php_orchestra_model.document.content.class%
            - %php_orchestra_backoffice.document.content_attribute.class%
        tags:
            - {name: form.type, alias: content}

    # Language form field type
    php_orchestra_backoffice.type.language:
        class: %php_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %php_orchestra_backoffice.orchestra_choice.front_language%
            - "orchestra_language"
        tags:
            - { name: form.type, alias: orchestra_language }

    # Direction form field type
    php_orchestra_backoffice.type.direction:
        class: %php_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %php_orchestra_backoffice.orchestra_choice.direction%
            - "orchestra_direction"
        tags:
            - { name: form.type, alias: orchestra_direction }
