parameters:
    open_orchestra_user.repository.group.class: OpenOrchestra\UserBundle\Repository\GroupRepository

services:
    open_orchestra_user.repository.group:
        class: '%open_orchestra_user.repository.group.class%'
        factory:
            - '@object_manager'
            - 'getRepository'
        calls:
            - ['setAggregationQueryBuilder', ['@doctrine_mongodb.odm.default_aggregation_query']]
            - ['setFilterTypeManager', ['@open_orchestra_pagination.filter_type.manager']]
        arguments:
            - '%open_orchestra_user.document.group.class%'
