parameters:
    open_orchestra_backoffice.subscriber.update_statusable_element_published.class: OpenOrchestra\Backoffice\EventListener\UpdateStatusableElementPublished

services:
    open_orchestra_backoffice.listener.update_node_published:
        class: '%open_orchestra_backoffice.subscriber.update_statusable_element_published.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_model.repository.status'
            - '@object_manager'
        tags:
            - { name: kernel.event_listener, event: node.status, priority: 100, method: updateStatus}
    open_orchestra_backoffice.listener.update_content_published:
        class: '%open_orchestra_backoffice.subscriber.update_statusable_element_published.class%'
        arguments:
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_model.repository.status'
            - '@object_manager'
        tags:
            - { name: kernel.event_listener, event: content.status, priority: 100, method: updateStatus}
