parameters:
    open_orchestra_backoffice.reference.manager.class: OpenOrchestra\Backoffice\Reference\ReferenceManager
    open_orchestra_backoffice.reference.strategy.keyword_in_block.class: OpenOrchestra\Backoffice\Reference\Strategies\KeywordInBlockReferenceStrategy
    open_orchestra_backoffice.reference.strategy.keyword_in_content.class: OpenOrchestra\Backoffice\Reference\Strategies\KeywordInContentReferenceStrategy
    open_orchestra_backoffice.reference.strategy.keyword_in_content_type.class: OpenOrchestra\Backoffice\Reference\Strategies\KeywordInContentTypeReferenceStrategy
    open_orchestra_backoffice.reference.strategy.keyword_in_node.class: OpenOrchestra\Backoffice\Reference\Strategies\KeywordInNodeReferenceStrategy
    open_orchestra_backoffice.reference.strategy.content_in_block.class: OpenOrchestra\Backoffice\Reference\Strategies\ContentInBlockReferenceStrategy
    open_orchestra_backoffice.reference.strategy.content_in_content.class: OpenOrchestra\Backoffice\Reference\Strategies\ContentInContentReferenceStrategy
    open_orchestra_backoffice.reference.strategy.node_in_block.class: OpenOrchestra\Backoffice\Reference\Strategies\NodeInBlockReferenceStrategy

services:
    open_orchestra_backoffice.reference.manager:
        class: '%open_orchestra_backoffice.reference.manager.class%'
        arguments:
            - '@object_manager'
    open_orchestra_backoffice.reference.strategy.keyword_in_block:
        class: '%open_orchestra_backoffice.reference.strategy.keyword_in_block.class%'
        arguments:
            - '@open_orchestra_model.repository.keyword'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
    open_orchestra_backoffice.reference.strategy.keyword_in_content:
        class: '%open_orchestra_backoffice.reference.strategy.keyword_in_content.class%'
        arguments:
            - '@open_orchestra_model.repository.keyword'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
    open_orchestra_backoffice.reference.strategy.keyword_in_content_type:
        class: '%open_orchestra_backoffice.reference.strategy.keyword_in_content_type.class%'
        arguments:
            - '@open_orchestra_model.repository.keyword'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
    open_orchestra_backoffice.reference.strategy.keyword_in_node:
        class: '%open_orchestra_backoffice.reference.strategy.keyword_in_node.class%'
        arguments:
            - '@open_orchestra_model.repository.keyword'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
    open_orchestra_backoffice.reference.strategy.content_in_block:
        class: '%open_orchestra_backoffice.reference.strategy.content_in_block.class%'
        arguments:
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_bbcode.parser'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
    open_orchestra_backoffice.reference.strategy.content_in_content:
        class: '%open_orchestra_backoffice.reference.strategy.content_in_content.class%'
        arguments:
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_bbcode.parser'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }

    open_orchestra_backoffice.reference.strategy.node_in_block:
        class: '%open_orchestra_backoffice.reference.strategy.node_in_block.class%'
        arguments:
            - '@open_orchestra_backoffice.context_manager'
            - '@open_orchestra_bbcode.parser'
            - '@open_orchestra_model.repository.node'
        tags:
            - { name: open_orchestra_backoffice.reference.strategy }
