parameters:
    open_orchestra_backoffice.role:
        role_access_tree_general_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_general_node
        role_access_update_general_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_general_node
        role_access_tree_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_node
        role_access_create_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_node
        role_access_update_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_node
        role_access_delete_node :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_node
        role_access_move_tree :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_node
        role_access_tree_template :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template
        role_access_create_template :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template
        role_access_update_template :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template
        role_access_delete_template :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template
        role_access_tree_template_flex :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template_flex
        role_access_create_template_flex :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template_flex
        role_access_update_template_flex :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template_flex
        role_access_delete_template_flex :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_template_flex
        role_access_content_type_for_content :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_for_content
        role_access_create_content_type_for_content :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_for_content
        role_access_update_content_type_for_content :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_for_content
        role_access_delete_content_type_for_content :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_for_content
        role_access_content_type :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_content_type
        role_access_create_content_type :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_content_type
        role_access_update_content_type :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_content_type
        role_access_delete_content_type :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_content_type
        role_access_redirection :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_redirection
        role_access_create_redirection :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_redirection
        role_access_update_redirection :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_redirection
        role_access_delete_redirection :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_redirection
        role_access_api_client :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_api_client
        role_access_create_api_client :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_api_client
        role_access_update_api_client :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_api_client
        role_access_delete_api_client :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_api_client
        role_access_keyword :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_keyword
        role_access_create_keyword :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_keyword
        role_access_update_keyword :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_keyword
        role_access_delete_keyword :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_keyword
        role_access_deleted :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_deleted
        role_access_restore :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_deleted
        role_access_status :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_status
        role_access_create_status :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_status
        role_access_update_status :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_status
        role_access_delete_status :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_status
        role_access_theme :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_theme
        role_access_create_theme :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_theme
        role_access_update_theme :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_theme
        role_access_delete_theme :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_theme
        role_access_site :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_site
        role_access_create_site :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_site
        role_access_update_site :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_site
        role_access_delete_site :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_site
        role_access_group :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_group
        role_access_create_group :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_group
        role_access_update_group :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_group
        role_access_delete_group :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_group
        role_access_role :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_role
        role_access_create_role :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_role
        role_access_update_role :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_role
        role_access_delete_role :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_role
