parameters:
    php_orchestra_backoffice.manager.context.class: PHPOrchestra\Backoffice\Context\ContextManager
    php_orchestra_backoffice.listener.translate_value_initializer.class: PHPOrchestra\BackofficeBundle\EventListener\TranslateValueInitializerListener
    php_orchestra_backoffice.manager.translation_choice.class: PHPOrchestra\Backoffice\Manager\TranslationChoiceManager
    php_orchestra_backoffice.twig_extension.translation_choice.class: PHPOrchestra\BackofficeBundle\Twig\TranslationChoiceExtension
    php_orchestra_backoffice.manager.area.class: PHPOrchestra\BackofficeBundle\Manager\AreaManager
    php_orchestra_backoffice.manager.node.class: PHPOrchestra\BackofficeBundle\Manager\NodeManager
    php_orchestra_backoffice.manager.media_folder.class: PHPOrchestra\BackofficeBundle\Manager\FolderManager

services:
    php_orchestra_backoffice.context_manager:
        class: "%php_orchestra_backoffice.manager.context.class%"
        arguments: [@session, @php_orchestra_model.repository.site, "%kernel.default_locale%"]
    php_orchestra.manager.current_site:
        alias: php_orchestra_backoffice.context_manager
    php_orchestra_backoffice.listener.translate_value_initializer:
        class: %php_orchestra_backoffice.listener.translate_value_initializer.class%
        arguments:
            - %php_orchestra_base.languages_availables%
    php_orchestra_backoffice.manager.translation_choice:
        class: %php_orchestra_backoffice.manager.translation_choice.class%
        arguments:
            - @php_orchestra_backoffice.context_manager
    php_orchestra_backoffice.twig_extension.translation_choice:
        class: %php_orchestra_backoffice.twig_extension.translation_choice.class%
        arguments:
            - @php_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: twig.extension}
    php_orchestra_backoffice.manager.area:
        class: %php_orchestra_backoffice.manager.area.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager
    php_orchestra_backoffice.manager.node:
        class: %php_orchestra_backoffice.manager.node.class%
        arguments: [@php_orchestra_model.repository.node]
    php_orchestra_backoffice.manager.media_folder:
        class: %php_orchestra_backoffice.manager.media_folder.class%
        arguments: [@php_orchestra_model.repository.media_folder, @php_orchestra_model.repository.media, @doctrine.odm.mongodb.document_manager]
