parameters:
    open_orchestra_backoffice.subscriber.update_child_node_path.class            : OpenOrchestra\Backoffice\EventSubscriber\UpdateChildNodePathSubscriber
    open_orchestra_backoffice.subscriber.update_redirection_node.class           : OpenOrchestra\Backoffice\EventSubscriber\UpdateRedirectionNodeSubscriber
    open_orchestra_backoffice.subscriber.flush_node_clache.class                 : OpenOrchestra\Backoffice\EventSubscriber\FlushNodeCacheSubscriber
    open_orchestra_backoffice.subscriber.block_menu_cache.class                  : OpenOrchestra\Backoffice\EventSubscriber\BlockMenuCacheSubscriber
    open_orchestra_backoffice.subscriber.content_update_cache.class              : OpenOrchestra\Backoffice\EventSubscriber\ContentUpdateCacheSubscriber
    open_orchestra_backoffice.subscriber.content_type_update_cache.class         : OpenOrchestra\Backoffice\EventSubscriber\ContentTypeUpdateCacheSubscriber
    open_orchestra_backoffice.subscriber.content_type.class                      : OpenOrchestra\Backoffice\EventSubscriber\ContentTypeSubscriber
    open_orchestra_backoffice.subscriber.delete_node.class                       : OpenOrchestra\Backoffice\EventSubscriber\DeleteNodeSubscriber
    open_orchestra_backoffice.subscriber.delete_content.class                    : OpenOrchestra\Backoffice\EventSubscriber\DeleteContentSubscriber
    open_orchestra_backoffice.subscriber.update_route_document.class             : OpenOrchestra\Backoffice\EventSubscriber\UpdateRouteDocumentSubscriber
    open_orchestra_backoffice.subscriber.create_root_node.class                  : OpenOrchestra\Backoffice\EventSubscriber\CreateMandatoryNodesSubscriber
    open_orchestra_backoffice.subscriber.update_site_alias_redirection_site.class: OpenOrchestra\Backoffice\EventSubscriber\UpdateSiteAliasRedirectionSiteSubscriber
    open_orchestra_backoffice.subscriber.block_form_type.class                   : OpenOrchestra\Backoffice\EventSubscriber\BlockFormTypeSubscriber
    open_orchestra_backoffice.subscriber.update_reference.class                  : OpenOrchestra\Backoffice\EventSubscriber\UpdateReferenceSubscriber
    open_orchestra_backoffice.subscriber.update_history_list.class               : OpenOrchestra\Backoffice\EventSubscriber\UpdateHistoryListSubscriber
    open_orchestra_backoffice.subscriber.content_type_type.class                 : OpenOrchestra\Backoffice\EventSubscriber\ContentTypeTypeSubscriber
    open_orchestra_backoffice.subscriber.content_type_statusable.class           : OpenOrchestra\Backoffice\EventSubscriber\ContentTypeStatusableSubscriber
    open_orchestra_backoffice.subscriber.sortable_collection.class               : OpenOrchestra\Backoffice\EventSubscriber\SortableCollectionSubscriber
    open_orchestra_backoffice.subscriber.field_type.class                        : OpenOrchestra\Backoffice\EventSubscriber\FieldTypeTypeSubscriber
    open_orchestra_backoffice.subscriber.special_page_choice.class               : OpenOrchestra\Backoffice\EventSubscriber\SpecialPageChoiceSubscriber
    open_orchestra_backoffice.subscriber.website.class                           : OpenOrchestra\Backoffice\EventSubscriber\WebSiteSubscriber
    open_orchestra_backoffice.subscriber.update_embedded_status.class            : OpenOrchestra\Backoffice\EventSubscriber\UpdateEmbeddedStatusSubscriber
    open_orchestra_backoffice.subscriber.update_node_site_alias.class            : OpenOrchestra\Backoffice\EventSubscriber\UpdateNodeSiteAliasSubscriber

services:
    open_orchestra_backoffice.subscriber.update_child_node_path:
        class: '%open_orchestra_backoffice.subscriber.update_child_node_path.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@event_dispatcher'
            - '@open_orchestra_backoffice.context_manager'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_redirection_node:
        class: '%open_orchestra_backoffice.subscriber.update_redirection_node.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_backoffice.manager.redirection'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.flush_node_clache:
        class: '%open_orchestra_backoffice.subscriber.flush_node_clache.class%'
        arguments:
            - '@open_orchestra_display.manager.cacheable'
            - '@open_orchestra_base.manager.tag'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.block_menu_cache:
        class: '%open_orchestra_backoffice.subscriber.block_menu_cache.class%'
        arguments:
            - '@open_orchestra_display.manager.cacheable'
            - '@open_orchestra_base.manager.tag'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.content_update_cache:
        class: '%open_orchestra_backoffice.subscriber.content_update_cache.class%'
        arguments:
            - '@open_orchestra_display.manager.cacheable'
            - '@open_orchestra_base.manager.tag'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.content_type_update_cache:
        class: '%open_orchestra_backoffice.subscriber.content_type_update_cache.class%'
        arguments:
            - '@open_orchestra_display.manager.cacheable'
            - '@open_orchestra_base.manager.tag'
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.content_type:
        class: '%open_orchestra_backoffice.subscriber.content_type.class%'
        arguments:
            - '@open_orchestra_model.repository.content_type'
            - '@open_orchestra_model.repository.status'
            - '%open_orchestra_model.document.content_attribute.class%'
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
            - '%open_orchestra_backoffice.field_types%'
            - '@open_orchestra_backoffice.value_transformer.manager'
            - '@translator'
            - '@event_dispatcher'

    open_orchestra_backoffice.subscriber.delete_node:
        class: '%open_orchestra_backoffice.subscriber.delete_node.class%'
        arguments:
            - '@object_manager'
            - '%open_orchestra_model.document.trash_item.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.delete_content:
        class: '%open_orchestra_backoffice.subscriber.delete_content.class%'
        arguments:
            - '@object_manager'
            - '%open_orchestra_model.document.trash_item.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_route_document:
        class: '%open_orchestra_backoffice.subscriber.update_route_document.class%'
        arguments:
            - '@object_manager'
            - '@open_orchestra_backoffice.manager.route_document'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.create_root_node:
        class: '%open_orchestra_backoffice.subscriber.create_root_node.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.node'
            - '@open_orchestra_model.repository.status'
            - '@object_manager'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_site_alias_redirection_site:
        class: '%open_orchestra_backoffice.subscriber.update_site_alias_redirection_site.class%'
        arguments:
            - '@object_manager'
            - '@open_orchestra_backoffice.manager.redirection'
            - '@open_orchestra_model.repository.node'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.block_form_type:
        class: '%open_orchestra_backoffice.subscriber.block_form_type.class%'
        arguments:
            - '%open_orchestra_backoffice.block.fixed_attributes%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_reference:
        class: '%open_orchestra_backoffice.subscriber.update_reference.class%'
        arguments:
            - '@open_orchestra_backoffice.reference.manager'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_history_list:
        class: '%open_orchestra_backoffice.subscriber.update_history_list.class%'
        arguments:
            - '@security.token_storage'
            - '@object_manager'
            - '%open_orchestra_model.document.history.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.content_type_type:
        class: '%open_orchestra_backoffice.subscriber.content_type_type.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.content_type_statusable:
        class: '%open_orchestra_backoffice.subscriber.content_type_statusable.class%'
        arguments:
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_model.repository.status'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.sortable_collection:
        class: '%open_orchestra_backoffice.subscriber.sortable_collection.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.field_type:
        class: '%open_orchestra_backoffice.subscriber.field_type.class%'
        arguments:
            - '%open_orchestra_backoffice.options%'
            - '%open_orchestra_backoffice.field_types%'
            - '%open_orchestra_model.document.field_option.class%'
            - '%open_orchestra_model.document.field_type.class%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.special_page_choice:
        class: '%open_orchestra_backoffice.subscriber.special_page_choice.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_backoffice.context_manager'
            - '%open_orchestra_backoffice.special_page_name%'
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.website:
        class: '%open_orchestra_backoffice.subscriber.website.class%'
        arguments:
            - '@session'

    open_orchestra_backoffice.subscriber.update_embedded_status:
        class: '%open_orchestra_backoffice.subscriber.update_embedded_status.class%'
        arguments:
            - ['@open_orchestra_model.repository.node', '@open_orchestra_model.repository.content']
        tags:
            - { name: kernel.event_subscriber }

    open_orchestra_backoffice.subscriber.update_node_site_alias:
        class: '%open_orchestra_backoffice.subscriber.update_node_site_alias.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.node'
            - '@open_orchestra_model.repository.node'
            - '@object_manager'
        tags:
            - { name: kernel.event_subscriber }
