parameters:
    open_orchestra_backoffice.subscriber.update_child_node_path.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateChildNodePathSubscriber
    open_orchestra_backoffice.subscriber.update_node_redirection.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateNodeRedirectionSubscriber
    open_orchestra_backoffice.subscriber.flush_node_clache.class: OpenOrchestra\BackofficeBundle\EventSubscriber\FlushNodeCacheSubscriber
    open_orchestra_backoffice.subscriber.change_content_status.class: OpenOrchestra\BackofficeBundle\EventSubscriber\ChangeContentStatusSubscriber

services:
    open_orchestra_backoffice.subscriber.update_child_node_path:
        class: %open_orchestra_backoffice.subscriber.update_child_node_path.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @service_container
            - @open_orchestra.manager.current_site
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_node_redirection:
        class: %open_orchestra_backoffice.subscriber.update_node_redirection.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.manager.redirection
            - @open_orchestra.manager.current_site
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.flush_node_clache:
        class: %open_orchestra_backoffice.subscriber.flush_node_clache.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.change_content_status:
        class: %open_orchestra_backoffice.subscriber.change_content_status.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
