parameters:
    open_orchestra_backoffice.subscriber.update_child_node_path.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateChildNodePathSubscriber
    open_orchestra_backoffice.subscriber.update_node_redirection.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateNodeRedirectionSubscriber
    open_orchestra_backoffice.subscriber.flush_node_clache.class: OpenOrchestra\BackofficeBundle\EventSubscriber\FlushNodeCacheSubscriber
    open_orchestra_backoffice.subscriber.change_content_status.class: OpenOrchestra\BackofficeBundle\EventSubscriber\ChangeContentStatusSubscriber
    open_orchestra_backoffice.subscriber.content_type.class: OpenOrchestra\BackofficeBundle\EventSubscriber\ContentTypeSubscriber
    open_orchestra_backoffice.subscriber.update_status.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateStatusSubscriber
    open_orchestra_backoffice.subscriber.add_content_button.class: OpenOrchestra\BackofficeBundle\EventSubscriber\AddContentSubmitButtonSubscriber

services:
    open_orchestra_backoffice.subscriber.update_child_node_path:
        class: %open_orchestra_backoffice.subscriber.update_child_node_path.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @event_dispatcher
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_node_redirection:
        class: %open_orchestra_backoffice.subscriber.update_node_redirection.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.manager.redirection
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.flush_node_clache:
        class: %open_orchestra_backoffice.subscriber.flush_node_clache.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.change_content_status:
        class: %open_orchestra_backoffice.subscriber.change_content_status.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.content_type:
        class: %open_orchestra_backoffice.subscriber.content_type.class%
        arguments:
            - @open_orchestra_model.repository.content_type
            - %open_orchestra_model.document.content_attribute.class%
            - @open_orchestra_backoffice.manager.translation_choice
            - %open_orchestra_backoffice.field_types%
            - @open_orchestra_backoffice.value_transformer.manager
            - @translator
    open_orchestra_backoffice.subscriber.update_status:
        class: %open_orchestra_backoffice.subscriber.update_status.class%
        arguments:
            - @open_orchestra_backoffice.authorize_status_change_manager
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.add_content_button:
           class: %open_orchestra_backoffice.subscriber.add_content_button.class%
           arguments:
               - @open_orchestra_model.repository.content
