parameters:
    open_orchestra_backoffice.template_set :
        default:
            label: open_orchestra_backoffice.template_set.default.label
            templates:
                default:
                    label: open_orchestra_backoffice.template_set.default.template_name.default
                    template: default/default.html
                full_page:
                    label: open_orchestra_backoffice.template_set.default.template_name.full_page
                    template: full_page.html
            styles:
                highlight: 
                    label : open_orchestra_backoffice.template_set.default.style.highlight
                paragraph: 
                    label : open_orchestra_backoffice.template_set.default.style.paragraph
        custom:
            label: open_orchestra_backoffice.template_set.custom.label
            templates:
                login:
                    label: open_orchestra_backoffice.template_set.custom.template_name.login
                    template: login.html
            styles:
                column: 
                    label : open_orchestra_backoffice.template_set.custom.style.column
                    