parameters:
    open_orchestra_backoffice.manager.context_backoffice.class: OpenOrchestra\Backoffice\Context\TestContextManager

services:
    open_orchestra_backoffice.context_backoffice_manager:
        class: '%open_orchestra_backoffice.manager.context_backoffice.class%'
        arguments:
          - '@session'
          - '@security.token_storage'
          - '%kernel.default_locale%'
          - '@open_orchestra_model.repository.site'
          - '@security.authorization_checker'
