parameters:
    open_orchestra_backoffice.manager.context.class: OpenOrchestra\Backoffice\Context\TestContextManager

services:
    open_orchestra_backoffice.context_manager:
        class: '%open_orchestra_backoffice.manager.context.class%'
        arguments:
          - '@open_orchestra_model.repository.site'
          - '%kernel.default_locale%'
