parameters:
    open_orchestra_backoffice.transformer.embedkeywords_to_keywords.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\EmbedKeywordsToKeywordsTransformer
    open_orchestra_backoffice.transformer.video_url_to_id.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\VideoUrlToIdTransformer
    open_orchestra_backoffice.transformer.choices_option_to_array.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\ChoicesOptionToArrayTransformer
    open_orchestra_backoffice.transformer.choice_array_to_string.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\ChoiceArrayToStringTransformer
    open_orchestra_backoffice.transformer.choice_string_to_array.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\ChoiceStringToArrayTransformer
    open_orchestra_backoffice.transformer.bbcode_to_html.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\BBcodeToHtmlTransformer
    open_orchestra_backoffice.transformer.reference_to_embed.class: OpenOrchestra\BackofficeBundle\Form\DataTransformer\ReferenceToEmbedTransformer

services:
    open_orchestra_backoffice.transformer.embedkeywords_to_keywords:
        class: %open_orchestra_backoffice.transformer.embedkeywords_to_keywords.class%
        arguments:
            - @open_orchestra_model.repository.keyword
            - @open_orchestra_model.helper.suppress_special_character
            - %open_orchestra_model.document.embed_keyword.class%
            - %open_orchestra_model.document.keyword.class%
            - @security.authorization_checker
    open_orchestra_backoffice.transformer.video_url_to_id:
        class: %open_orchestra_backoffice.transformer.video_url_to_id.class%
    open_orchestra_backoffice.transformer.choice_array_to_string:
        class: %open_orchestra_backoffice.transformer.choice_array_to_string.class%
    open_orchestra_backoffice.transformer.choice_string_to_array:
        class: %open_orchestra_backoffice.transformer.choice_string_to_array.class%
    open_orchestra_backoffice.transformer.choices_option_to_array:
        class: %open_orchestra_backoffice.transformer.choices_option_to_array.class%
        arguments:
            - @open_orchestra_model.helper.suppress_special_character
    open_orchestra_backoffice.transformer.bbcode_to_html:
        class: %open_orchestra_backoffice.transformer.bbcode_to_html.class%
        arguments:
            - @open_orchestra_bbcode.parser
    open_orchestra_backoffice.transformer.reference_to_embed:
        class: %open_orchestra_backoffice.transformer.reference_to_embed.class%
        arguments:
            - @open_orchestra_model.manager.content_for_embed
