parameters:
    open_orchestra_backoffice.transformer.video_url_to_id.class: OpenOrchestra\Backoffice\Form\DataTransformer\VideoUrlToIdTransformer
    open_orchestra_backoffice.transformer.choices_option_to_array.class: OpenOrchestra\Backoffice\Form\DataTransformer\ChoicesOptionToArrayTransformer
    open_orchestra_backoffice.transformer.bbcode_to_html.class: OpenOrchestra\Backoffice\Form\DataTransformer\BBcodeToHtmlTransformer
    open_orchestra_backoffice.transformer.reference_to_embed.class: OpenOrchestra\Backoffice\Form\DataTransformer\ReferenceToEmbedTransformer
    open_orchestra_backoffice.transformer.block_to_array.class: OpenOrchestra\Backoffice\Form\DataTransformer\BlockToArrayTransformer
    open_orchestra_backoffice.transformer.csv_to_reference_keyword.class: OpenOrchestra\Backoffice\Form\DataTransformer\CsvToReferenceKeywordTransformer
    open_orchestra_backoffice.transformer.condition_to_reference_keyword.class: OpenOrchestra\Backoffice\Form\DataTransformer\ConditionToReferenceKeywordTransformer
    open_orchestra_backoffice.transformer.content_type_order_field.class: OpenOrchestra\Backoffice\Form\DataTransformer\ContentTypeOrderFieldTransformer
    open_orchestra_backoffice.transformer.collection.class: OpenOrchestra\Backoffice\Form\DataTransformer\CollectionTransformer

services:
    open_orchestra_backoffice.transformer.video_url_to_id:
        class: '%open_orchestra_backoffice.transformer.video_url_to_id.class%'
    open_orchestra_backoffice.transformer.choices_option_to_array:
        class: '%open_orchestra_backoffice.transformer.choices_option_to_array.class%'
        arguments:
            - '@open_orchestra_model.helper.suppress_special_character'
    open_orchestra_backoffice.transformer.bbcode_to_html:
        class: '%open_orchestra_backoffice.transformer.bbcode_to_html.class%'
        arguments:
            - '@open_orchestra_bbcode.parser'
    open_orchestra_backoffice.transformer.reference_to_embed:
        class: '%open_orchestra_backoffice.transformer.reference_to_embed.class%'
        arguments:
            - '@open_orchestra_model.manager.content_for_embed'
            - '@object_manager'
            - '%open_orchestra_model.document.content.class%'
    open_orchestra_backoffice.transformer.block_to_array:
        class: '%open_orchestra_backoffice.transformer.block_to_array.class%'
    open_orchestra_backoffice.transformer.csv_to_reference_keyword:
        class: '%open_orchestra_backoffice.transformer.csv_to_reference_keyword.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.keyword_to_document'
            - '@open_orchestra_model.repository.keyword'
    open_orchestra_backoffice.transformer.condition_to_reference_keyword:
        class: '%open_orchestra_backoffice.transformer.condition_to_reference_keyword.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.keyword_to_document'
            - '@open_orchestra_model.repository.keyword'
    open_orchestra_backoffice.transformer.content_type_order_field:
        class: '%open_orchestra_backoffice.transformer.content_type_order_field.class%'
    open_orchestra_backoffice.transformer.check_list_collection:
        class: '%open_orchestra_backoffice.transformer.collection.class%'
        arguments:
            - 'check_list_collection'
    open_orchestra_backoffice.transformer.check_list:
        class: '%open_orchestra_backoffice.transformer.collection.class%'
        arguments:
            - 'check_list'
    open_orchestra_backoffice.transformer.tree_list_collection:
        class: '%open_orchestra_backoffice.transformer.collection.class%'
        arguments:
            - 'tree_list_collection'
    open_orchestra_backoffice.transformer.tree_list:
        class: '%open_orchestra_backoffice.transformer.collection.class%'
        arguments:
            - 'tree_list'
