parameters:
    open_orchestra_backoffice.twig_extension.muli_languages_choice.class: OpenOrchestra\BackofficeBundle\Twig\MultiLanguagesChoiceExtension

services:
    open_orchestra_backoffice.twig_extension.muli_languages_choice:
        class: '%open_orchestra_backoffice.twig_extension.muli_languages_choice.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
        tags:
            - {name: twig.extension}
