parameters:
    open_orchestra_backoffice.twig_extension.translation_choice.class: OpenOrchestra\BackofficeBundle\Twig\TranslationChoiceExtension
    open_orchestra_backoffice.twig_extension.muli_languages_choice.class: OpenOrchestra\BackofficeBundle\Twig\MultiLanguagesChoiceExtension
    open_orchestra_backoffice.twig_extension.block_icon.class: OpenOrchestra\BackofficeBundle\Twig\BlockIconExtension
    open_orchestra_backoffice.twig_extension.navigation_panel.class: OpenOrchestra\BackofficeBundle\Twig\NavigationPanelExtension

services:
    open_orchestra_backoffice.twig_extension.translation_choice:
        class: '%open_orchestra_backoffice.twig_extension.translation_choice.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.translation_choice'
        deprecated: ~
        tags:
            - {name: twig.extension}
    open_orchestra_backoffice.twig_extension.muli_languages_choice:
        class: '%open_orchestra_backoffice.twig_extension.muli_languages_choice.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
        tags:
            - {name: twig.extension}
    open_orchestra_backoffice.twig_extension.block_icon:
        class: '%open_orchestra_backoffice.twig_extension.block_icon.class%'
        arguments:
            - '@open_orchestra_backoffice.display_icon_manager'
        tags:
            - {name: twig.extension}
    open_orchestra_backoffice.twig_extension.navigation_panel:
        class: '%open_orchestra_backoffice.twig_extension.navigation_panel.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: twig.extension}
