parameters:
    open_orchestra_model.validatorcontent_template.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\ContentTemplateValidator
    open_orchestra_model.validator.block_node_pattern.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\BlockNodePatternValidator
    open_orchestra_model.validator.authorize_edition.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\AuthorizeEditionValidator
    open_orchestra_model.validator.restore_node.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\RestoreNodeValidator

services:
    open_orchestra_model.validatorcontent_template:
        class: %open_orchestra_model.validatorcontent_template.class%
        arguments:
            - @twig
        tags:
            - { name: validator.constraint_validator, alias: content_template}
    open_orchestra_model.validator.block_node_pattern:
        class: %open_orchestra_model.validator.block_node_pattern.class%
        arguments:
            - @open_orchestra_backoffice.generate_form_manager
        tags:
            - { name: validator.constraint_validator, alias: block_node_pattern}
    open_orchestra_model.validator.restore_node:
        class: %open_orchestra_model.validator.restore_node.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: validator.constraint_validator, alias: restore_node}
