parameters:
    open_orchestra_backoffice.value_transformer.manager.class: OpenOrchestra\BackofficeBundle\EventSubscriber\DataTransformer\ValueTransformerManager
    open_orchestra_backoffice.value_transformer.array.class: OpenOrchestra\BackofficeBundle\EventSubscriber\DataTransformer\ArrayToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.integer.class: OpenOrchestra\BackofficeBundle\EventSubscriber\DataTransformer\IntegerToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.null.class: OpenOrchestra\BackofficeBundle\EventSubscriber\DataTransformer\NullToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.object.class: OpenOrchestra\BackofficeBundle\EventSubscriber\DataTransformer\ObjectToHtmlStringTransformer

services:
    open_orchestra_backoffice.value_transformer.manager:
        class: %open_orchestra_backoffice.value_transformer.manager.class%

    open_orchestra_backoffice.value_transformer.array:
            class: %open_orchestra_backoffice.value_transformer.array.class%
            tags:
                - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.integer:
            class: %open_orchestra_backoffice.value_transformer.integer.class%
            tags:
                - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.null:
        class: %open_orchestra_backoffice.value_transformer.null.class%
        tags:
            - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.object:
        class: %open_orchestra_backoffice.value_transformer.object.class%
        tags:
            - { name: open_orchestra_backoffice.value_transformer.strategy }
