parameters:
    open_orchestra_backoffice.value_transformer.manager.class: OpenOrchestra\Backoffice\ValueTransformer\ValueTransformerManager
    open_orchestra_backoffice.value_transformer.array.class: OpenOrchestra\Backoffice\ValueTransformer\Strategies\ArrayToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.integer.class: OpenOrchestra\Backoffice\ValueTransformer\Strategies\IntegerToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.null.class: OpenOrchestra\Backoffice\ValueTransformer\Strategies\NullToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.document.class: OpenOrchestra\Backoffice\ValueTransformer\Strategies\DocumentToHtmlStringTransformer
    open_orchestra_backoffice.value_transformer.object.class: OpenOrchestra\Backoffice\ValueTransformer\Strategies\ObjectToHtmlStringTransformer

services:
    open_orchestra_backoffice.value_transformer.manager:
        class: %open_orchestra_backoffice.value_transformer.manager.class%

    open_orchestra_backoffice.value_transformer.array:
            class: %open_orchestra_backoffice.value_transformer.array.class%
            tags:
                - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.integer:
            class: %open_orchestra_backoffice.value_transformer.integer.class%
            tags:
                - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.null:
        class: %open_orchestra_backoffice.value_transformer.null.class%
        tags:
            - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.content:
        class: %open_orchestra_backoffice.value_transformer.document.class%
        arguments:
            - name
        tags:
            - { name: open_orchestra_backoffice.value_transformer.strategy }
    open_orchestra_backoffice.value_transformer.object:
        class: %open_orchestra_backoffice.value_transformer.object.class%
        tags:
            - { name: open_orchestra_backoffice.value_transformer.strategy }
