parameters:
    open_orchestra_backoffice.voter.group_site.class: OpenOrchestra\BackofficeBundle\Security\Authorization\Voter\GroupSiteVoter
    open_orchestra_backoffice.voter.node_group_role.class: OpenOrchestra\BackofficeBundle\Security\Authorization\Voter\NodeGroupRoleVoter

services:
    open_orchestra_backoffice.voter.group_site:
        class: %open_orchestra_backoffice.voter.group_site.class%
        arguments:
            - @open_orchestra_backoffice.context_manager
            - @open_orchestra_model.repository.site
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.node_group_role:
        class: %open_orchestra_backoffice.voter.node_group_role.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: security.voter }
