parameters:
    open_orchestra_backoffice.voter.group_site.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\GroupSiteVoter
    open_orchestra_backoffice.voter.node_group_role.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\NodeGroupRoleVoter
    open_orchestra_backoffice.voter.statusable.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\StatusableVoter
    open_orchestra_backoffice.voter.node_version.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\NodeVersionVoter
    open_orchestra_backoffice.voter.content_version.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\ContentVersionVoter
    open_orchestra_backoffice.voter.delete_status.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\DeleteStatusVoter
    open_orchestra_backoffice.voter.delete_role.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\DeleteRoleVoter
    open_orchestra_backoffice.voter.delete_node.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\DeleteNodeVoter
    security.access.role_hierarchy_voter.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\RoleHierarchyVoter

services:
    open_orchestra_backoffice.voter.group_site:
        class: %open_orchestra_backoffice.voter.group_site.class%
        arguments:
            - @open_orchestra_backoffice.context_manager
            - @open_orchestra_model.repository.site
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.node_group_role:
        class: %open_orchestra_backoffice.voter.node_group_role.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.node_version:
        class: %open_orchestra_backoffice.voter.node_version.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.content_version:
        class: %open_orchestra_backoffice.voter.content_version.class%
        arguments:
            - @open_orchestra_model.repository.content
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.statusable:
        class: %open_orchestra_backoffice.voter.statusable.class%
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.delete_status:
        class: %open_orchestra_backoffice.voter.delete_status.class%
        arguments:
            - @open_orchestra_backoffice.usage_finder.status
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.delete_role:
        class: %open_orchestra_backoffice.voter.delete_role.class%
        arguments:
            - @open_orchestra_backoffice.usage_finder.role
        tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.delete_node:
        class: %open_orchestra_backoffice.voter.delete_node.class%
        tags:
            - { name: security.voter }
