parameters:
    open_orchestra_backoffice.voter.node.class:                OpenOrchestra\Backoffice\Security\Authorization\Voter\NodeVoter
    open_orchestra_backoffice.voter.content.class:             OpenOrchestra\Backoffice\Security\Authorization\Voter\ContentVoter
    open_orchestra_backoffice.voter.trash_item.class:          OpenOrchestra\Backoffice\Security\Authorization\Voter\TrashItemVoter
    open_orchestra_backoffice.voter.site_administration.class: OpenOrchestra\Backoffice\Security\Authorization\Voter\SiteAdministrationVoter
    open_orchestra_backoffice.voter.developer_tool.class:      OpenOrchestra\Backoffice\Security\Authorization\Voter\DeveloperToolVoter

services:
    open_orchestra_backoffice.voter.node:
       class: '%open_orchestra_backoffice.voter.node.class%'
       tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.content:
       class: '%open_orchestra_backoffice.voter.content.class%'
       tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.trash_item:
       class: '%open_orchestra_backoffice.voter.trash_item.class%'
       tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.site_administration:
       class: '%open_orchestra_backoffice.voter.site_administration.class%'
       tags:
            - { name: security.voter }
    open_orchestra_backoffice.voter.developer_tool:
       class: '%open_orchestra_backoffice.voter.developer_tool.class%'
       tags:
            - { name: security.voter }
