parameters:
    open_orchestra_api.transformer.node.class                          : OpenOrchestra\ApiBundle\Transformer\NodeTransformer
    open_orchestra_api.transformer.node_collection.class               : OpenOrchestra\ApiBundle\Transformer\NodeCollectionTransformer
    open_orchestra_api.transformer.nodes_tree.class                    : OpenOrchestra\ApiBundle\Transformer\NodesTreeTransformer
    open_orchestra_api.transformer.node_tree_leaf.class                : OpenOrchestra\ApiBundle\Transformer\NodeTreeLeafTransformer
    open_orchestra_api.transformer.node_tree.class                     : OpenOrchestra\ApiBundle\Transformer\NodeTreeTransformer
    open_orchestra_api.transformer.area.class                          : OpenOrchestra\ApiBundle\Transformer\AreaTransformer
    open_orchestra_api.transformer.block.class                         : OpenOrchestra\ApiBundle\Transformer\BlockTransformer
    open_orchestra_api.transformer.block_collection.class              : OpenOrchestra\ApiBundle\Transformer\BlockCollectionTransformer
    open_orchestra_api.transformer.block_component_collection.class    : OpenOrchestra\ApiBundle\Transformer\BlockComponentCollectionTransformer
    open_orchestra_api.transformer.block_component.class               : OpenOrchestra\ApiBundle\Transformer\BlockComponentTransformer
    open_orchestra_api.transformer.content_type.class                  : OpenOrchestra\ApiBundle\Transformer\ContentTypeTransformer
    open_orchestra_api.transformer.content_type_collection.class       : OpenOrchestra\ApiBundle\Transformer\ContentTypeCollectionTransformer
    open_orchestra_api.transformer.content.class                       : OpenOrchestra\ApiBundle\Transformer\ContentTransformer
    open_orchestra_api.transformer.content_attribute.class             : OpenOrchestra\ApiBundle\Transformer\ContentAttributeTransformer
    open_orchestra_api.transformer.content_collection.class            : OpenOrchestra\ApiBundle\Transformer\ContentCollectionTransformer
    open_orchestra_api.transformer.site.class                          : OpenOrchestra\ApiBundle\Transformer\SiteTransformer
    open_orchestra_api.transformer.site_alias.class                    : OpenOrchestra\ApiBundle\Transformer\SiteAliasTransformer
    open_orchestra_api.transformer.site_collection.class               : OpenOrchestra\ApiBundle\Transformer\SiteCollectionTransformer
    open_orchestra_api.transformer.theme.class                         : OpenOrchestra\ApiBundle\Transformer\ThemeTransformer
    open_orchestra_api.transformer.theme_collection.class              : OpenOrchestra\ApiBundle\Transformer\ThemeCollectionTransformer
    open_orchestra_api.transformer.redirection.class                   : OpenOrchestra\ApiBundle\Transformer\RedirectionTransformer
    open_orchestra_api.transformer.redirection_collection.class        : OpenOrchestra\ApiBundle\Transformer\RedirectionCollectionTransformer
    open_orchestra_api.transformer.field_type.class                    : OpenOrchestra\ApiBundle\Transformer\FieldTypeTransformer
    open_orchestra_api.transformer.keyword.class                       : OpenOrchestra\ApiBundle\Transformer\KeywordTransformer
    open_orchestra_api.transformer.keyword_collection.class            : OpenOrchestra\ApiBundle\Transformer\KeywordCollectionTransformer
    open_orchestra_api.transformer.link.class                          : OpenOrchestra\ApiBundle\Transformer\LinkTransformer
    open_orchestra_api.transformer.api_client.class                    : OpenOrchestra\ApiBundle\Transformer\ApiClientTransformer
    open_orchestra_api.transformer.api_client_collection.class         : OpenOrchestra\ApiBundle\Transformer\ApiClientCollectionTransformer
    open_orchestra_api.transformer.datatable_translation.class         : OpenOrchestra\ApiBundle\Transformer\DatatableTranslationTransformer
    open_orchestra_api.transformer.datatable_collection_parameter.class: OpenOrchestra\ApiBundle\Transformer\DatatableCollectionParameterTransformer
    open_orchestra_api.transformer.datatable_entity_parameter.class    : OpenOrchestra\ApiBundle\Transformer\DatatableEntityParameterTransformer
    open_orchestra_api.transformer.datatable_column_parameter.class    : OpenOrchestra\ApiBundle\Transformer\DatatableColumnParameterTransformer
    open_orchestra_api.transformer.trash_item.class                    : OpenOrchestra\ApiBundle\Transformer\TrashItemTransformer
    open_orchestra_api.transformer.trash_item_collection.class         : OpenOrchestra\ApiBundle\Transformer\TrashItemCollectionTransformer
    open_orchestra_api.transformer.translation.class                   : OpenOrchestra\ApiBundle\Transformer\TranslationTransformer

services:
    open_orchestra_api.transformer.node:
        class: '%open_orchestra_api.transformer.node.class%'
        arguments:
            - '%open_orchestra_api.facade.node.class%'
            - '@open_orchestra_base.manager.encryption'
            - '@open_orchestra_model.repository.site'
            - '@open_orchestra_model.repository.status'
            - '@event_dispatcher'
            - '@security.authorization_checker'
            - '@open_orchestra_model.repository.node'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.node_collection:
        class: '%open_orchestra_api.transformer.node_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.node_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.node_tree_leaf:
        class: '%open_orchestra_api.transformer.node_tree_leaf.class%'
        arguments:
            - '%open_orchestra_api.facade.node.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.node_tree:
        class: '%open_orchestra_api.transformer.node_tree.class%'
        arguments:
            - '%open_orchestra_api.facade.node_tree.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.nodes_tree:
        class: '%open_orchestra_api.transformer.nodes_tree.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.area:
        class: '%open_orchestra_api.transformer.area.class%'
        arguments:
            - '%open_orchestra_api.facade.area.class%'
            - '@security.authorization_checker'
            - '%open_orchestra_model.document.area.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.block:
        class: '%open_orchestra_api.transformer.block.class%'
        arguments:
            - '%open_orchestra_api.facade.block.class%'
            - '@open_orchestra_backoffice.display_block_manager'
            - '@open_orchestra_backoffice.manager.block_configuration'
            - '@translator'
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_model.repository.block'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.block_collection:
        class: '%open_orchestra_api.transformer.block_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.block_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.block_component:
        class: '%open_orchestra_api.transformer.block_component.class%'
        arguments:
            - '%open_orchestra_api.facade.block_component.class%'
            - '@open_orchestra_backoffice.manager.block_configuration'
            - '@translator'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.block_component_collection:
        class: '%open_orchestra_api.transformer.block_component_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.block_component_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.content_type:
        class: '%open_orchestra_api.transformer.content_type.class%'
        arguments:
            - '%open_orchestra_api.facade.content_type.class%'
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
            - '@open_orchestra_model.repository.content'
            - '@open_orchestra_model.repository.content_type'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.content_type_collection:
        class: '%open_orchestra_api.transformer.content_type_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.content_type_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.content:
        class: '%open_orchestra_api.transformer.content.class%'
        arguments:
            - '%open_orchestra_api.facade.content.class%'
            - '@open_orchestra_model.repository.status'
            - '@open_orchestra_model.repository.content'
            - '@security.authorization_checker'
            - '@open_orchestra_backoffice.context_manager'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.content_attribute:
        class: '%open_orchestra_api.transformer.content_attribute.class%'
        arguments:
            - '%open_orchestra_api.facade.content_attribute.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.content_collection:
        class: '%open_orchestra_api.transformer.content_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.content_collection.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.site:
        class: '%open_orchestra_api.transformer.site.class%'
        arguments:
            - '%open_orchestra_api.facade.site.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.site_alias:
        class: '%open_orchestra_api.transformer.site_alias.class%'
        arguments:
            - '%open_orchestra_api.facade.site_alias.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.site_collection:
        class: '%open_orchestra_api.transformer.site_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.site_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.theme:
        class: '%open_orchestra_api.transformer.theme.class%'
        arguments:
            - '%open_orchestra_api.facade.theme.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.theme_collection:
        class: '%open_orchestra_api.transformer.theme_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.theme_collection.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.redirection:
        class: '%open_orchestra_api.transformer.redirection.class%'
        arguments:
            - '%open_orchestra_api.facade.redirection.class%'
            - '@security.authorization_checker'
            - '@open_orchestra_model.repository.redirection'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.redirection_collection:
        class: '%open_orchestra_api.transformer.redirection_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.redirection_collection.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.field_type:
        class: '%open_orchestra_api.transformer.field_type.class%'
        arguments:
            - '%open_orchestra_api.facade.field_type.class%'
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
            - '%open_orchestra_backoffice.field_types%'
        tags:
            - { name: open_orchestra_api.transformer.strategy }

    open_orchestra_api.transformer.keyword:
        class: '%open_orchestra_api.transformer.keyword.class%'
        arguments:
            - '%open_orchestra_api.facade.keyword.class%'
            - '@security.authorization_checker'
            - '@open_orchestra_model.repository.keyword'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.keyword_collection:
        class: '%open_orchestra_api.transformer.keyword_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.keyword_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.link:
        class: '%open_orchestra_api.transformer.link.class%'
        arguments:
            - '%open_orchestra_api.facade.link.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.api_client:
        class: '%open_orchestra_api.transformer.api_client.class%'
        arguments:
            - '%open_orchestra_api.facade.api_client.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.api_client_collection:
        class: '%open_orchestra_api.transformer.api_client_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.api_client_collection.class%'
            - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.datatable_translation:
        class: '%open_orchestra_api.transformer.datatable_translation.class%'
        arguments:
            - '%open_orchestra_api.facade.datatable_translation.class%'
            - '@translator'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.datatable_collection_parameter:
        class: '%open_orchestra_api.transformer.datatable_collection_parameter.class%'
        arguments:
            - '%open_orchestra_api.facade.datatable_collection_parameter.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.datatable_entity_parameter:
        class: '%open_orchestra_api.transformer.datatable_entity_parameter.class%'
        arguments:
            - '%open_orchestra_api.facade.datatable_entity_parameter.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.datatable_column_paramater:
        class: '%open_orchestra_api.transformer.datatable_column_parameter.class%'
        arguments:
            - '%open_orchestra_api.facade.datatable_column_parameter.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.trash_item:
        class: '%open_orchestra_api.transformer.trash_item.class%'
        arguments:
          - '%open_orchestra_api.facade.trash_item.class%'
          - '@security.authorization_checker'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.trash_item_collection:
        class: '%open_orchestra_api.transformer.trash_item_collection.class%'
        arguments:
            - '%open_orchestra_api.facade.trash_item_collection.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    open_orchestra_api.transformer.translation:
        class: '%open_orchestra_api.transformer.translation.class%'
        arguments:
            - '%open_orchestra_api.facade.translation.class%'
        tags:
            - { name: open_orchestra_api.transformer.strategy}
