parameters:
    open_orchestra_group.business_rules_manager.group.class: OpenOrchestra\GroupBundle\BusinessRules\Strategies\GroupStrategy

services:
    open_orchestra_group.business_rules_manager.group:
        class: '%open_orchestra_group.business_rules_manager.group.class%'
        arguments:
            - '@open_orchestra_user.repository.user'
        tags:
            - { name: open_orchestra_backoffice.business_rules.strategy }
