parameters:
    open_orchestra_group.type.group_list.class: OpenOrchestra\GroupBundle\Form\Type\GroupListType
    open_orchestra_group.type.group_element.class: OpenOrchestra\GroupBundle\Form\Type\GroupElementType
    open_orchestra_group.type.group.class: OpenOrchestra\GroupBundle\Form\Type\GroupType

services:
    open_orchestra_group.type.group_list:
        class: '%open_orchestra_group.type.group_list.class%'
        arguments:
            - '@open_orchestra_group.transformer.group_list_to_array'
        tags:
            - { name: form.type, alias: oo_group_list }
    open_orchestra_group.type.group_element:
        class: '%open_orchestra_group.type.group_element.class%'
        arguments:
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
            - '@open_orchestra_user.repository.group'
            - '@security.authorization_checker'
        tags:
            - { name: form.type, alias: oo_group_element }
    open_orchestra_group.type.group:
        class: '%open_orchestra_group.type.group.class%'
        arguments:
            - '%open_orchestra_user.document.group.class%'
            - '%open_orchestra_base.administration_languages%'
        tags:
            - { name: form.type, alias: oo_group }
