parameters:
    open_orchestra_group.generate_perimeter_manager.class: OpenOrchestra\Backoffice\GeneratePerimeter\GeneratePerimeterManager
    open_orchestra_group.generate_perimeter.node.class   : OpenOrchestra\Backoffice\GeneratePerimeter\Strategy\NodeGeneratePerimeterStrategy

services:
    open_orchestra_group.generate_perimeter_manager:
        class: '%open_orchestra_group.generate_perimeter_manager.class%'

    open_orchestra_group.generate_perimeter.node:
        class: '%open_orchestra_group.generate_perimeter.node.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_backoffice.context_backoffice_manager'
        tags:
            - { name: open_orchestra_group.generate_perimeter.strategy }
