resolve_target_documents:
    OpenOrchestra\Backoffice\Model\ModelGroupRoleInterface: OpenOrchestra\GroupBundle\Document\ModelGroupRole
    OpenOrchestra\Backoffice\Model\PerimeterInterface: OpenOrchestra\GroupBundle\Document\Perimeter
