resolve_target_documents:
    OpenOrchestra\Backoffice\Model\NodeGroupRoleInterface: OpenOrchestra\GroupBundle\Document\NodeGroupRole
    OpenOrchestra\Backoffice\Model\DocumentGroupRoleInterface: OpenOrchestra\GroupBundle\Document\DocumentGroupRole
