parameters:
    open_orchestra_user.document.group.class: OpenOrchestra\GroupBundle\Document\Group
    open_orchestra_group.type.group_choice.class: OpenOrchestra\GroupBundle\Form\Type\GroupDocumentType

services:
    open_orchestra_group.type.group_choice:
        class: %open_orchestra_group.type.group_choice.class%
        arguments:
            - %open_orchestra_user.document.group.class%
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: form.type, alias: oo_group_choice }
