parameters:
    open_orchestra_group.subscriber.soft_delete_group.class : OpenOrchestra\GroupBundle\EventSubscriber\SoftDeleteGroupSubscriber
    open_orchestra_group.subscriber.group_member.class: OpenOrchestra\GroupBundle\EventSubscriber\GroupMemberSubscriber
    open_orchestra_group.subscriber.group_perimeter.class: OpenOrchestra\GroupBundle\EventSubscriber\GroupPerimeterSubscriber

services:
    open_orchestra_group.subscriber.soft_delete_group:
        class: '%open_orchestra_group.subscriber.soft_delete_group.class%'
        arguments:
            - '@open_orchestra_user.repository.group'
    open_orchestra_group.subscriber.group_member:
        class: '%open_orchestra_group.subscriber.group_member.class%'
        arguments:
            - '@open_orchestra_user.repository.user'
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_group.subscriber.group_perimeter:
        class: '%open_orchestra_group.subscriber.group_perimeter.class%'
        tags:
            - { name: kernel.event_subscriber }
