parameters:
    open_orchestra_user_admin.navigation_panel.user.parameters :
        username :
          title : open_orchestra_user_admin.table.username
          visible : true
          activateColvis : true
          searchField : date
        groups :
          title : open_orchestra_user_admin.table.groups
          visible : true
          activateColvis : true
          searchField : date
