parameters:
    open_orchestra_user_admin.oauth2.strategy.resource_owner_password_grant.class: OpenOrchestra\UserAdminBundle\OAuth2\Strategy\ResourceOwnerPasswordGrantStrategy

services:
    open_orchestra_user_admin.oauth2.strategy.resource_owner_password_grant:
        class: '%open_orchestra_user_admin.oauth2.strategy.resource_owner_password_grant.class%'
        arguments:
            - '@open_orchestra_api.repository.api_client'
            - '@open_orchestra_user.repository.user'
            - '@security.encoder_factory'
            - '@serializer'
            - '@validator'
            - '@open_orchestra_api.manager.access_token'
            - '@open_orchestra_api.repository.access_token'
        tags:
            - { name: open_orchestra_api.oauth2.strategy }

