parameters:
    open_orchestra_user.role:
        role_access_user :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_user
        role_access_create_user :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_user
        role_access_update_user :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_user
        role_access_delete_user :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_user
