parameters:
    open_orchestra_user_admin.role_hierarchy:
        ROLE_PLATFORM_ADMIN: [ROLE_USER, ROLE_KEYWORD]
        ROLE_DEVELOPER:      [ROLE_PLATFORM_ADMIN, ROLE_ALLOWED_TO_SWITCH]

services:
    security.access.role_hierarchy_voter:
        class: '%security.access.role_hierarchy_voter.class%'
        arguments:
            - '@security.role_hierarchy'
        tags:
            - { name: security.voter, priority: "245" }
    security.access.simple_role_voter:
        class: '%security.access.simple_role_voter.class%'
