parameters:
    open_orchestra_user_admin.subscriber.delete_group.class: OpenOrchestra\UserAdminBundle\EventSubscriber\DeleteGroupSubscriber
    open_orchestra_user_admin.subscriber.user_profile.class: OpenOrchestra\UserAdminBundle\EventSubscriber\UserProfilSubscriber
    open_orchestra_user_admin.subscriber.user_group.class: OpenOrchestra\UserAdminBundle\EventSubscriber\UserGroupsSubscriber

services:
    open_orchestra_user_admin.subscriber.delete_group:
        class: '%open_orchestra_user_admin.subscriber.delete_group.class%'
        arguments:
            - '@object_manager'
            - '@open_orchestra_user.repository.user'
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_user_admin.subscriber.user_profile:
        class: '%open_orchestra_user_admin.subscriber.user_profile.class%'
        arguments:
            - '@security.authorization_checker'
    open_orchestra_user_admin.subscriber.user_group:
        class: '%open_orchestra_user_admin.subscriber.user_group.class%'
